### ISSUE TITLE
Array variable has incorrect number of subscripts

### ISSUE THREAD

**Issue by SPG1091** [MeteorTheLizard/SMITE-Optimizer#12] opened 2022-11-28 19:16 UTC
I get this window when I go to apply with any settings. Cant create a bug dump as the program closes when I select ok.
I just want my new 6800 xt to run it better than 1660ti :'(

![smite error](https://user-images.githubusercontent.com/119355101/204361339-f4a9c193-387c-48d5-bba2-1c3c23eb5f35.PNG)

**Comment by MeteorTheLizard** [comment] 2022-11-29 16:25
Duplicate of #11 

> Have you launched SMITE at least once on your system before?

**Comment by SPG1091** [comment] 2022-11-29 17:07
Yes, many times.

**Comment by MeteorTheLizard** [comment] 2022-11-29 17:42
I require more information to figure out what's going on.

Have you launched the SMITE Optimizer on your system before changing to your new graphics card and did it work?

Have you reinstalled your system after changing to the new graphics card?

What exactly does the program do after you start it? From your description I take that it immediately crashes upon reaching the home screen, is that correct?

_DevNote: L:6062: refers to ExitLoop / EndIf - cannot be the cause of array dimensions exceeding!_

**Comment by SPG1091** [comment] 2022-11-29 17:56
I have not used smite optimiser prior to installing the new GPU.
I have not reinstalled, just literally took the old GPU out and stuck the new one in.
The program starts and runs and I can adjust all the parameters, however, once I select verify and repair or apply changes, the loading bar starts, gets maybe halfway then displays the shown error, when I ok the shown error the program closes.

**Comment by MeteorTheLizard** [comment] 2022-11-29 18:07
Have you launched SMITE at least once after installing your new GPU?

Also it should be possible to create a debug dump. You can do that in the "Debug" tab. Click the text and it will open a window where you have to select the location to save it in. Attach the file here.

**Comment by MeteorTheLizard** [comment] 2022-11-29 19:45
Another potential solution would be to head into the debug tab and disable the verify/repair integrity routine. It's possible that the HIVEs are outdated.

**Comment by SPG1091** [comment] 2022-11-30 17:59
Disabling the verify and repair routine has been successful. Thank you for all your help!

**Comment by MeteorTheLizard** [comment] 2022-11-30 18:24
Fixed in v1.3.5

**Closed by MeteorTheLizard** 2022-11-30 18:24 UTC
Labels: bug, fixed
